// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_ZipShellExt_AddTo7zCommand()
{
    return winrt::detach_abi(winrt::make<winrt::ZipShellExt::factory_implementation::AddTo7zCommand>());
}
WINRT_EXPORT namespace winrt::ZipShellExt
{
    AddTo7zCommand::AddTo7zCommand() :
        AddTo7zCommand(make<ZipShellExt::implementation::AddTo7zCommand>())
    {
    }
}
