// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#include "winrt/ZipShellExt.h"
namespace winrt::ZipShellExt::implementation
{
    template <typename D, typename B, typename... I>
    struct WINRT_IMPL_EMPTY_BASES AddTo7zCommand_base : implements<D, ZipShellExt::AddTo7zCommand, B, no_module_lock, I...>
    {
        using base_type = AddTo7zCommand_base;
        using class_type = ZipShellExt::AddTo7zCommand;
        using implements_type = typename AddTo7zCommand_base::implements_type;
        using implements_type::implements_type;
        using composable_base = B;
        hstring GetRuntimeClassName() const
        {
            return L"ZipShellExt.AddTo7zCommand";
        }
    };
}
namespace winrt::ZipShellExt::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES AddTo7zCommandT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = ZipShellExt::AddTo7zCommand;

        hstring GetRuntimeClassName() const
        {
            return L"ZipShellExt.AddTo7zCommand";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_ADDTO7ZCOMMAND_XAML_G_H) || __has_include("AddTo7zCommand.xaml.g.h")

#include "AddTo7zCommand.xaml.g.h"

#else

namespace winrt::ZipShellExt::implementation
{
    template <typename D, typename... I>
    using AddTo7zCommandT = AddTo7zCommand_base<D, I...>;
}

#endif
