// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_ZipShellExt_BaseExplorerCommand()
{
    return winrt::detach_abi(winrt::make<winrt::ZipShellExt::factory_implementation::BaseExplorerCommand>());
}
WINRT_EXPORT namespace winrt::ZipShellExt
{
    BaseExplorerCommand::BaseExplorerCommand() :
        BaseExplorerCommand(make<ZipShellExt::implementation::BaseExplorerCommand>())
    {
    }
}
