// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#include "winrt/ZipShellExt.h"
namespace winrt::ZipShellExt::implementation
{
    template <typename D, typename B, typename... I>
    struct WINRT_IMPL_EMPTY_BASES ExtractToCommand_base : implements<D, ZipShellExt::ExtractToCommand, B, no_module_lock, I...>
    {
        using base_type = ExtractToCommand_base;
        using class_type = ZipShellExt::ExtractToCommand;
        using implements_type = typename ExtractToCommand_base::implements_type;
        using implements_type::implements_type;
        using composable_base = B;
        hstring GetRuntimeClassName() const
        {
            return L"ZipShellExt.ExtractToCommand";
        }
    };
}
namespace winrt::ZipShellExt::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES ExtractToCommandT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = ZipShellExt::ExtractToCommand;

        hstring GetRuntimeClassName() const
        {
            return L"ZipShellExt.ExtractToCommand";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_EXTRACTTOCOMMAND_XAML_G_H) || __has_include("ExtractToCommand.xaml.g.h")

#include "ExtractToCommand.xaml.g.h"

#else

namespace winrt::ZipShellExt::implementation
{
    template <typename D, typename... I>
    using ExtractToCommandT = ExtractToCommand_base<D, I...>;
}

#endif
