// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#include "pch.h"
#include "winrt/base.h"
void* winrt_make_ZipShellExt_AddTo7zCommand();
void* winrt_make_ZipShellExt_AddToZipCommand();
void* winrt_make_ZipShellExt_BaseExplorerCommand();
void* winrt_make_ZipShellExt_CompressAndEmailCommand();
void* winrt_make_ZipShellExt_ExtractToCommand();
void* winrt_make_ZipShellExt_SevenZipCommand();

bool __stdcall winrt_can_unload_now() noexcept
{
    if (winrt::get_module_lock())
    {
        return false;
    }

    winrt::clear_factory_cache();
    return true;
}

void* __stdcall winrt_get_activation_factory([[maybe_unused]] std::wstring_view const& name)
{
    auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
    {
        return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
    };

    if (requal(name, L"ZipShellExt.AddTo7zCommand"))
    {
        return winrt_make_ZipShellExt_AddTo7zCommand();
    }

    if (requal(name, L"ZipShellExt.AddToZipCommand"))
    {
        return winrt_make_ZipShellExt_AddToZipCommand();
    }

    if (requal(name, L"ZipShellExt.BaseExplorerCommand"))
    {
        return winrt_make_ZipShellExt_BaseExplorerCommand();
    }

    if (requal(name, L"ZipShellExt.CompressAndEmailCommand"))
    {
        return winrt_make_ZipShellExt_CompressAndEmailCommand();
    }

    if (requal(name, L"ZipShellExt.ExtractToCommand"))
    {
        return winrt_make_ZipShellExt_ExtractToCommand();
    }

    if (requal(name, L"ZipShellExt.SevenZipCommand"))
    {
        return winrt_make_ZipShellExt_SevenZipCommand();
    }

    return nullptr;
}

int32_t __stdcall WINRT_CanUnloadNow() noexcept
{
#ifdef _WRL_MODULE_H_
    if (!::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().Terminate())
    {
        return 1;
    }
#endif

    return winrt_can_unload_now() ? 0 : 1;
}

int32_t __stdcall WINRT_GetActivationFactory(void* classId, void** factory) noexcept try
{
    std::wstring_view const name{ *reinterpret_cast<winrt::hstring*>(&classId) };
    *factory = winrt_get_activation_factory(name);

    if (*factory)
    {
        return 0;
    }

#ifdef _WRL_MODULE_H_
    return ::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().GetActivationFactory(static_cast<HSTRING>(classId), reinterpret_cast<::IActivationFactory**>(factory));
#else
    return winrt::hresult_class_not_available(name).to_abi();
#endif
}
catch (...) { return winrt::to_hresult(); }
