// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#include "winrt/ZipShellExt.h"
namespace winrt::ZipShellExt::implementation
{
    template <typename D, typename B, typename... I>
    struct WINRT_IMPL_EMPTY_BASES SevenZipCommand_base : implements<D, ZipShellExt::SevenZipCommand, B, no_module_lock, I...>
    {
        using base_type = SevenZipCommand_base;
        using class_type = ZipShellExt::SevenZipCommand;
        using implements_type = typename SevenZipCommand_base::implements_type;
        using implements_type::implements_type;
        using composable_base = B;
        hstring GetRuntimeClassName() const
        {
            return L"ZipShellExt.SevenZipCommand";
        }
    };
}
namespace winrt::ZipShellExt::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES SevenZipCommandT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = ZipShellExt::SevenZipCommand;

        hstring GetRuntimeClassName() const
        {
            return L"ZipShellExt.SevenZipCommand";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_SEVENZIPCOMMAND_XAML_G_H) || __has_include("SevenZipCommand.xaml.g.h")

#include "SevenZipCommand.xaml.g.h"

#else

namespace winrt::ZipShellExt::implementation
{
    template <typename D, typename... I>
    using SevenZipCommandT = SevenZipCommand_base<D, I...>;
}

#endif
